const hotelInfo = {
  nombre: "El Cielo",
  iniciales: "EC",
  descripcion:
    "Redefiniendo el panorama de la hospitalidad a través de un diseño meticuloso y un servicio intuitivo.",
  correo: "reservas@hotelelielo.com",
  anioActual: new Date().getFullYear(),
};

const roomsData = [
  {
    id: 1,
    name: "Habitación Estándar con Balcón",
    estado: true,
    description:
      "Disfruta de una estancia cómoda en el corazón de Arequipa. Esta habitación cuenta con un balcón privado con vista a la calle colonial, escritorio de trabajo ideal para viajeros de negocios y una excelente iluminación natural.",
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1000&auto=format&fit=crop",
    ],
    location: "Piso 3 • Cerca a la Plaza de Armas",
    price: 180,
    bathroom: "Baño Privado con Agua Caliente 24h",
    size: "25 m²",
    bed: "Cama Matrimonial",
    capacity: "2 Personas",
    type: "Matrimonial",
    sede: "Arequipa",
    adults: 2,
    kids: 0,
    people: 2,
    extra: "Wi-Fi de Alta Velocidad",
    badge: "Más Reservada",
    balcon: true,
    view: "Vista al Volcán Misti",
    amenities: [
      { i: "tv", n: "TV Cable" },
      { i: "thermostat", n: "Calefacción" },
      { i: "coffee_maker", n: "Hervidor eléctrico" },
    ],
    bookedDates: [
      { start: "2026-04-29", end: "2026-04-30" },
      { start: "2026-11-10", end: "2026-11-15" },
    ],
  },
  {
    id: 2,
    name: "Habitación Económica Interior",
    estado: true,
    description:
      "La opción ideal para quienes buscan tranquilidad y descanso al mejor precio. Al ser una habitación interior, está aislada del ruido de la calle. Perfecta para un descanso reparador tras un día de tour.",
    images: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1000&auto=format&fit=crop",
    ],
    location: "Piso 1 • Zona Silenciosa",
    price: 130,
    bathroom: "Baño Privado con Ducha",
    size: "18 m²",
    bed: "Cama Matrimonial (Full)",
    capacity: "2 Personas",
    type: "Matrimonial",
    sede: "Arequipa",
    adults: 2,
    kids: 0,
    people: 2,
    extra: "Desayuno incluido",
    badge: "Mejor Precio",
    balcon: false,
    view: "Sin vista (Interior)",
    amenities: [
      { i: "tv", n: "TV Cable" },
      { i: "wifi", n: "Wi-Fi Gratis" },
    ],
    bookedDates: [{ start: "2026-10-26", end: "2026-10-30" }],
  },
  {
    id: 3,
    name: "Habitación Doble Clásica",
    estado: true,
    description:
      "Habitación espaciosa equipada con dos camas, ideal para amigos o colegas de trabajo. Cuenta con amplios ventanales que permiten la entrada del sol arequipeño y un ambiente acogedor.",
    images: [
      "https://images.unsplash.com/photo-1566195992011-5f6b21e539aa?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590490359683-658d3d23f972?q=80&w=1000&auto=format&fit=crop",
    ],
    location: "Piso 2 • Vista Interna",
    price: 210,
    bathroom: "Baño Privado con Agua Caliente 24h",
    size: "30 m²",
    bed: "2 Camas de 1.5 Plazas",
    capacity: "2 Personas",
    type: "Doble",
    sede: "Arequipa",
    adults: 2,
    kids: 0,
    people: 2,
    extra: "Escritorio amplio",
    badge: "Ideal Grupos",
    balcon: false,
    view: "Vista al Patio Colonial",
    amenities: [
      { i: "tv", n: "TV Cable" },
      { i: "thermostat", n: "Calefacción" },
      { i: "desk", n: "Zona de trabajo" },
    ],
    bookedDates: [], // status booked? true / false
  },
  {
    id: 4,
    name: "Suite Triple Arequipeña",
    estado: true,
    description:
      "Habitación de gran tamaño diseñada para familias. Ofrece un ambiente seguro y cómodo con capacidad para tres personas, ubicada en una zona estratégica del hotel para mayor comodidad.",
    images: [
      "https://images.unsplash.com/photo-1578683062331-624344936d97?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1000&auto=format&fit=crop",
    ],
    location: "Piso 2 • Vista a la Ciudad",
    price: 320,
    bathroom: "Baño Amplio con Tina",
    size: "45 m²",
    bed: "1 Cama King + 1 Cama Simple",
    capacity: "3 Personas",
    type: "Triple",
    sede: "Arequipa",
    adults: 2,
    kids: 1,
    people: 3,
    extra: "Frigobar incluido",
    badge: "Triple",
    balcon: true,
    view: "Vista a la Ciudad Blanca",
    amenities: [
      { i: "tv", n: "Smart TV" },
      { i: "fridge", n: "Frigobar" },
      { i: "coffee_maker", n: "Cafetera" },
    ],
    bookedDates: [{ start: "2026-10-24", end: "2026-10-25" }],
  },
];
